import { Entypo, Feather, FontAwesome, Ionicons } from "@expo/vector-icons";
import images from "./Images";

export const ItemSliderData = [
  {
    image: images.items[0],
  },
  {
    image: images.items[2],
  },
  {
    image: images.items[1],
  },
];

export const textData = [
  {
    id: "1",
    toggle: true,
    title: "How to add products",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic",
  },
  {
    id: "2",
    toggle: false,
    title: "How to add expenses",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic",
  },
  {
    id: "3",
    toggle: false,
    title: "Learn about invoice and receipts",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic",
  },
];
export const itemsData2 = [
  {
    id: "1",
    title: "Buggy Jeans the ehe eh",
    text: "description of the item and the problem is that",
    image: images.items[0],
    price: 33,
    totalItem: 50,
    itemLeft: 30,
    ceilingPrice: 20,
    sellingPrice: 33,
    discount: 0,
  },
  {
    id: "2",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
  {
    id: "4",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[2],
    price: 344,
    totalItem: 50,
    itemLeft: 30,
    ceilingPrice: 20,
    sellingPrice: 33,
    discount: 0,
  },
  {
    id: "6",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
  {
    id: "8",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
  {
    id: "9",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
  {
    id: "l6",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
  {
    id: "6ek",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
  {
    id: "6eke",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
  {
    id: "6ekdfd",
    title: "Jeans top",
    text: "description of the item",
    image: images.items[1],
    price: 344,
    totalItem: 80,
    itemLeft: 50,
    ceilingPrice: 200,
    sellingPrice: 323,
    discount: 0,
  },
];

export const chartData = {
  labels: ["January", "February", "March", "April", "May", "June"],
  datasets: [
    {
      data: [
        Math.random() * 100,
        Math.random() * 100,
        Math.random() * 100,
        Math.random() * 100,
        Math.random() * 100,
        Math.random() * 100,
      ],
    },
  ],
};

export const itemData = [
  {
    id: "1",
    title: "Rice and stew",
    image: images.items[0],
    price: 300,
  },
  {
    id: "2",
    title: "Grilled Meat",
    image: images.items[1],
    price: 100,
  },
  {
    id: "3",
    title: "Rice ball with Banana",
    image: images.items[2],
    price: 300,
  },
  {
    id: "k3",
    title: "Fresh Donuts",
    image: images.items[3],
    price: 300,
  },
];
export const cartsData = [
  {
    id: "1",
    title: "Rice and stew",
    image: images.items[0],
    price: 300,
    text: "description of the food goes here",
  },
  {
    id: "2",
    title: "Grilled Meat",
    image: images.items[1],
    price: 100,
    text: "description of the food goes here",
  },
  {
    id: "3",
    title: "Rice ball with Banana",
    image: images.items[2],
    price: 300,
    text: "description of the food goes here",
  },
  {
    id: "3dd",
    title: "Rice ball with Banana",
    image: images.items[2],
    price: 300,
    text: "description of the food goes here",
  },
];

export const categoriesData = [
  {
    id: "1",
    title: "Electronics",
    Icon: FontAwesome,
    iconName: "television",
    active: false,
  },
  {
    id: "2",
    title: "Entertainment",
    Icon: Feather,
    iconName: "speaker",
    active: true,
  },
  {
    id: "3",
    title: "Men's wear",
    Icon: Ionicons,
    iconName: "shirt",
    active: false,
  },
  {
    id: "5",
    title: "Games",
    Icon: Entypo,
    iconName: "game-controller",
    active: false,
  },
  {
    id: "6",
    title: "Health and food",
    Icon: Ionicons,
    iconName: "fast-food",
    active: false,
  },
  {
    id: "1d",
    title: "Electronics",
    Icon: FontAwesome,
    iconName: "television",
    active: false,
  },
  {
    id: "2e",
    title: "Entertainment",
    Icon: Feather,
    iconName: "speaker",
    active: false,
  },
  {
    id: "3d",
    title: "Men's wear",
    Icon: Ionicons,
    iconName: "shirt",
    active: false,
  },
  {
    id: "5e",
    title: "Games",
    Icon: Entypo,
    iconName: "game-controller",
    active: false,
  },
  {
    id: "6o",
    title: "Health and food",
    Icon: Ionicons,
    iconName: "fast-food",
    active: false,
  },
];

export const productArr = [
  {
    id: "1",
    title: "Head Phone",
    image: images.items[0],
    products: 50,
  },
  {
    id: "2",
    title: "Ladies Dress",
    image: images.items[1],
    products: 30,
  },
  {
    id: "3",
    title: "Men's Wear",
    image: images.items[2],
    products: 100,
  },
  {
    id: "2dd",
    title: "Ladies Dress",
    image: images.items[1],
    products: 30,
  },
  {
    id: "de1",
    title: "Head Phone",
    image: images.items[0],
    products: 50,
  },
  {
    id: "dedfd1",
    title: "Head Phone",
    image: images.items[0],
    products: 50,
  },
  {
    id: "de1df",
    title: "Head Phone",
    image: images.items[0],
    products: 50,
  },
  {
    id: "dedf",
    title: "Head Phone",
    image: images.items[0],
    products: 50,
  },
  {
    id: "odedf",
    title: "Head Phone",
    image: images.items[0],
    products: 50,
  },
  {
    id: "2djfd",
    title: "Ladies Dress",
    image: images.items[1],
    products: 30,
  },
  {
    id: "2dfdf",
    title: "Ladies Dress",
    image: images.items[1],
    products: 30,
  },
];
