import { ImageSourcePropType } from "react-native";

const images = {
  logo1: require("../assets/images/logo1.png"),
  logo2: require("../assets/images/logo2.png"),
  avatar: require("../assets/images/icons/avatar.png"),
  profile: require("../assets/images/profile.jpg"),
  cart: require("../assets/images/icons/cart1.png"),
  product: require("../assets/images/icons/shopping.png"),
  product2: require("../assets/images/icons/product.png"),
  sales2: require("../assets/images/icons/sales2.png"),
  sales1: require("../assets/images/icons/sales1.png"),
  pizza: require("../assets/images/pizza.png"),
  terms: require("../assets/images/icons/terms-and-conditions.png"),
  payments: require("../assets/images/icons/wallet.png"),
  changePawword: require("../assets/images/icons/reset.png"),
  business: require("../assets/images/icons/resume.png"),
  discount: require("../assets/images/icons/discount.png"),
  sales3: require("../assets/images/icons/sales.png"),
  expense: require("../assets/images/icons/expense.png"),
  profit: require("../assets/images/icons/profit.png"),
  motobike: require("../assets/images/icons/motorbike.png"),
  creditCard: require("../assets/images/icons/credit-card.png"),
  order: require("../assets/images/icons/shop.png"),
  records: require("../assets/images/icons/money-transfer.png"),
  client: require("../assets/images/icons/message.png"),
  message: require("../assets/images/icons/conversation.png"),
  vada: require("../assets/images/icons/voda.jpg"),
  mtn: require("../assets/images/icons/mtn.png"),
  airtel: require("../assets/images/icons/airtel.png"),
  masterCard: require("../assets/images/icons/master.png"),
  complete: require("../assets/images/icons/complete.png"),
  awaiting: require("../assets/images/icons/awaiting.png"),
  installment: require("../assets/images/icons/installment.png"),
  debter: require("../assets/images/icons/debter.png"),
  input: require("../assets/images/icons/input.png"),
  manageBGLogo: require("../assets/images/icons/svg1.png"),
  mogul: require("../assets/images/mogul.jpg"),
  swiper: [
    require("../assets/images/swiper/swiper1.png"),
    require("../assets/images/swiper/swiper2.png"),
    require("../assets/images/swiper/swiper3.png"),
    require("../assets/images/swiper/swiper4.png"),
    require("../assets/images/swiper/swiper5.png"),
    require("../assets/images/swiper/swiper6.png"),
    require("../assets/images/swiper/swiper7.png"),
  ],
  items: [
    require("../assets/images/items/item1.png"),
    require("../assets/images/items/item3.png"),
    require("../assets/images/items/item2.png"),
  ],
  ugora: [
    require("../assets/images/u.png"),
    require("../assets/images/g.png"),
    require("../assets/images/o.png"),
    require("../assets/images/r.png"),
    require("../assets/images/a.png"),
    require("../assets/images/gg.png"),
  ],
};

export default images;
